tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                    "on-primary-fixed": "#410004",
                    "secondary-fixed": "#eee1cc",
                    "on-secondary": "#363022",
                    "surface-bright": "#3d3836",
                    "on-secondary-fixed": "#211b0e",
                    "inverse-primary": "#aa3433",
                    "primary-fixed-dim": "#ffb3ae",
                    "on-background": "#e9e1dd",
                    "on-primary-fixed-variant": "#891c1e",
                    "on-tertiary-fixed-variant": "#6b3837",
                    "on-tertiary": "#502322",
                    "tertiary-fixed-dim": "#fcb5b1",
                    "tertiary-fixed": "#ffdad8",
                    "surface-container": "#231f1d",
                    "primary": "#ffb3ae",
                    "on-surface": "#e9e1dd",
                    "surface-container-low": "#1e1b19",
                    "on-primary-container": "#ffb7b1",
                    "on-error-container": "#ffdad6",
                    "on-secondary-fixed-variant": "#4e4637",
                    "secondary-fixed-dim": "#d1c5b1",
                    "on-error": "#690005",
                    "primary-container": "#9c2a2a",
                    "surface-variant": "#383431",
                    "secondary-container": "#504839",
                    "outline": "#a68a88",
                    "background": "#161311",
                    "inverse-surface": "#e9e1dd",
                    "surface": "#161311",
                    "error": "#ffb4ab",
                    "outline-variant": "#58413f",
                    "surface-container-lowest": "#110e0c",
                    "secondary": "#d1c5b1",
                    "on-tertiary-fixed": "#360e0f",
                    "on-surface-variant": "#dfbfbc",
                    "surface-container-highest": "#383431",
                    "on-primary": "#68000b",
                    "surface-container-high": "#2d2927",
                    "inverse-on-surface": "#34302d",
                    "error-container": "#93000a",
                    "surface-tint": "#ffb3ae",
                    "surface-dim": "#161311",
                    "tertiary-container": "#7a4544",
                    "on-secondary-container": "#c3b7a3",
                    "on-tertiary-container": "#feb7b4",
                    "tertiary": "#fcb5b1",
                    "primary-fixed": "#ffdad7"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "section-gap": "120px",
                    "container-max": "1140px",
                    "unit": "8px",
                    "gutter": "24px",
                    "margin-edge": "40px"
            },
            "fontFamily": {
                    "body-lg": ["Inter"],
                    "headline-lg": ["Noto Serif"],
                    "headline-xl": ["Noto Serif"],
                    "headline-md": ["Noto Serif"],
                    "body-md": ["Inter"],
                    "label-sm": ["Inter"]
            },
            "fontSize": {
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "400"}],
                    "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}]
            }
        },
    },
}